package fragment;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ProgressBar;
import javafx.stage.Stage;

public class ProgressBar1Controller implements Initializable {
	@FXML
	private ProgressBar progress_bar_1;
	@FXML
	private Button btn_close;

	class pg_Thread implements Runnable {

		@Override
		public void run() {
			// TODO Auto-generated method stub
			for (int i = 0; i < 100; i++) {
				progress_bar_1.setProgress(i / 100.0);
				try {
					Thread.sleep(100);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
	}

	// Event Listener on Button[#btn_close].onAction
	@FXML
	public void event_btn_close(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btn_close.getScene().getWindow();
		stage.close();
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		progress_bar_1.setProgress(0.0);
		Thread thread = new Thread(new pg_Thread());
		thread.start();
	}

}
