package fragment;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ProgressBar;
import javafx.stage.Stage;

public class ProgressBar2Controller implements Initializable {
	@FXML
	private ProgressBar progress_bar_2;
	@FXML
	private Button btn_close;
	@FXML
	private Button btn_scan;

	class pg_Thread implements Runnable {

		@Override
		public void run() {
			// TODO Auto-generated method stub
			for (int i = 0; i < 100; i++) {
				progress_bar_2.setProgress(i / 100.0);
				try {
					Thread.sleep(30);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}

	}

	// Event Listener on Button[#btn_close].onAction
	@FXML
	public void event_btn_close(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent root = FXMLLoader.load(getClass().getResource("/model/Third.fxml"));
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btn_scan].onAction
	@FXML
	public void event_scan(ActionEvent event) {
		// TODO Autogenerated
		Thread thread = new Thread(new pg_Thread());
		thread.start();
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		progress_bar_2.setProgress(0.0);

	}
}
