package fragment;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import fragment.ModelType;
import fragment.VideoType;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.layout.VBox;
import javafx.stage.DirectoryChooser;
import javafx.stage.Stage;

public class ThirdController implements Initializable {
    @FXML
    private TableView<ModelType> tableViewModel;
    @FXML
    private TableView<VideoType> tableViewVideo;
    @FXML
    private Button btnAdd;
    @FXML
    private Button btnChoose;
    @FXML
    private Button btnStart;
    @FXML
    private Button btnCheck;

    TableColumn<VideoType, String> videoColumn = new TableColumn<VideoType, String>("视频类别");
    TableColumn<ModelType, String> modelColumn = new TableColumn<ModelType, String>("当前训练任务");

    ObservableList<VideoType> list1 = FXCollections.observableArrayList();
    ObservableList<ModelType> list2 = FXCollections.observableArrayList();

    // Event Listener on Button[#btnAdd].onAction
    @FXML
    public void event_Add(ActionEvent event) {

        DirectoryChooser directoryChooser = new DirectoryChooser();
        File file = directoryChooser.showDialog(new Stage());
        String path = file.toString();
        String value = path.substring(path.lastIndexOf("\\") + 1);
        VideoType videoType1 = new VideoType(value);
        list1.add(videoType1);
        videoColumn.setCellValueFactory(cellData -> cellData.getValue().getVideoProperty());
        tableViewVideo.setItems(list1);
    }

    // Event Listener on Button[#btnChoose].onAction
    @FXML
    public void event_Choose(ActionEvent event) {
        VBox anchorPane = new VBox();
        anchorPane.setMinSize(200, 100);
        Label text = new Label("训练任务已经被选择，正在加入训练.....\\n成功加入训练，请选择添加的视频类型");
        Button button_Close = new Button("关闭");

        anchorPane.getChildren().addAll(text, button_Close);

        Stage stage = new Stage();
        Scene scene = new Scene(anchorPane);
        stage.setScene(scene);
        button_Close.setOnAction(new EventHandler<ActionEvent>() {

            @Override
            public void handle(ActionEvent arg0) {
                // TODO Auto-generated method stub
                stage.close();
            }
        });
        stage.show();
    }

    // Event Listener on Button[#btnStart].onAction
    @FXML
    public void event_Start(ActionEvent event) {
        // TODO Autogenerated
        try {
            Parent root = FXMLLoader.load(getClass().getResource("/model/ProgressBar1.fxml"));
            Scene scene = new Scene(root);
            Stage stage = new Stage();
            stage.setScene(scene);
            stage.show();
            setEnabledCheck();
        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    // Event Listener on Button[#btnCheck].onAction
    @FXML
    public void event_Check(ActionEvent event) {
        String osName = System.getProperty("os.name", "");
        if (osName.startsWith("Windows")) {
            // Windows
            if (java.awt.Desktop.isDesktopSupported()) {
                java.net.URI uri = java.net.URI.create("https://localhost:8080");
                java.awt.Desktop dp = java.awt.Desktop.getDesktop();
                if (dp.isSupported(java.awt.Desktop.Action.BROWSE)) {
                    try {
                        dp.browse(uri);
                    } catch (IOException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
        } else {
            // Ubuntu
            String url = "firefox localhost:8080";
            try {
                Runtime.getRuntime().exec(url);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

    @Override
    public void initialize(URL arg0, ResourceBundle arg1) {

        ModelType model1 = new ModelType("Task_Fire");
        ModelType model2 = new ModelType("Task_Gun");
        ModelType model3 = new ModelType("Task_Sword");

        list2.addAll(model1, model2, model3);
        modelColumn.setCellValueFactory(cellData -> cellData.getValue().getModelProperty());
        tableViewModel.setItems(list2);
        tableViewModel.getColumns().add(modelColumn);
        tableViewVideo.getColumns().add(videoColumn);

        btnCheck.setVisible(false);
    }

    public void setEnabledCheck() {
        btnCheck.setVisible(true);
    }
}
